api_platform:
  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
    html: [ 'text/html' ]
    multipart: ['multipart/form-data']
    json-patch: ['application/json-patch+json']