parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $batchSize: '%env(BATCH_SIZE)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'
